Downgrade libidn because Smart Google Enginieers FUCKED IT UP!
libidn 1.27+ is using a java.util.Arrays function that our beloved
Androiders forgot to implement:

https://code.google.com/p/android/issues/detail?id=10054

Because they added them with Gingerbread, the compiler won't warn you,
and the app crashes in evil ways on SDK<r9 devices. Thank you so much,
Google!

	Uncaught handler: thread main exiting due to uncaught exception
	java.lang.NoSuchMethodError: java.util.Arrays.binarySearch
		at gnu.inet.encoding.RangeSet.containsAnyCodePoint(RangeSet.java:338)
		at gnu.inet.encoding.Stringprep.nameprep$185c6b75(Stringprep.java:194)
		at gnu.inet.encoding.Stringprep.nameprep(Stringprep.java:146)
		at org.yaxim.androidclient.util.XMPPHelper.verifyJabberID(XMPPHelper.java:27)